<?php

namespace app\api\modules\v1\models;

use app\api\modules\v1\base\BaseActiveRecord;

/**
 * This is the model class for table "logs".
 *
 * @property int $id Идентификатор записи
 * @property int|null $log_type Тип логирования из таблицы log_types
 * @property string|null $table_name Название таблицы операции
 * @property int|null $event_type Идентификатор события из таблицы sql_events
 * @property string|null $object_info Информация идентификатора объекта с которым произведены действия
 * @property string|null $text Данные создания, обновления, удаления
 * @property string|null $created_at Дата создания записи
 * @property string|null $updated_at Дата обновления записи
 */
class Logs extends BaseActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'logs';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['log_type', 'event_type'], 'integer'],
            [['created_at', 'updated_at'], 'safe'],
            [['table_name', 'object_info'], 'string', 'max' => 255],
            [['text'], 'string'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'log_type' => 'Log Type',
            'table_name' => 'Table Name',
            'event_type' => 'Event Type',
            'object_info' => 'Object Info',
            'text' => 'Text',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->on(self::EVENT_BEFORE_INSERT, function() { $this->updated_at = null; });
    }

    public static function createErrorLog($err, $prKey, $modelName, $event_type)
    {
        $log = new Logs();

        $log->log_type = 0;
        $log->table_name = $modelName;
        $log->text .= '';
        $log->event_type = $event_type;

        if (!empty($prKey)) {
            $log->object_info = serialize($prKey);
        }

        if (!empty($err)) {
            $log->text = serialize($err);
        }

        $log->save();
    }
}
